/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupHospitalRouteImport } from './routes/signup-hospital'
import { Route as SignupDoctorRouteImport } from './routes/signup-doctor'
import { Route as SignupAmbulanceRouteImport } from './routes/signup-ambulance'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorDoctorIdRouteImport } from './routes/doctor.$doctorId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultRouteImport } from './routes/_authenticated/consult'
import { Route as AuthenticatedBookAmbulanceRouteImport } from './routes/_authenticated/book-ambulance'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedApplyDoctorRouteImport } from './routes/_authenticated/apply-doctor'
import { Route as AuthenticatedVideoAppointmentIdRouteImport } from './routes/_authenticated/video.$appointmentId'
import { Route as AuthenticatedTrackOrderOrderIdRouteImport } from './routes/_authenticated/track-order.$orderId'
import { Route as AuthenticatedTrackAmbulanceBookingIdRouteImport } from './routes/_authenticated/track-ambulance.$bookingId'
import { Route as AuthenticatedPayPaymentIdRouteImport } from './routes/_authenticated/pay.$paymentId'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedHospitalDepartmentsRouteImport } from './routes/_authenticated/hospital.departments'
import { Route as AuthenticatedHospitalDashboardRouteImport } from './routes/_authenticated/hospital.dashboard'
import { Route as AuthenticatedHospitalBranchesRouteImport } from './routes/_authenticated/hospital.branches'
import { Route as AuthenticatedHospitalBedsRouteImport } from './routes/_authenticated/hospital.beds'
import { Route as AuthenticatedDoctorWorkspaceRouteImport } from './routes/_authenticated/doctor.workspace'
import { Route as AuthenticatedDoctorTemplatesRouteImport } from './routes/_authenticated/doctor.templates'
import { Route as AuthenticatedDoctorScheduleRouteImport } from './routes/_authenticated/doctor.schedule'
import { Route as AuthenticatedDoctorPatientsRouteImport } from './routes/_authenticated/doctor.patients'
import { Route as AuthenticatedDoctorDashboardRouteImport } from './routes/_authenticated/doctor.dashboard'
import { Route as AuthenticatedDoctorAnalyticsRouteImport } from './routes/_authenticated/doctor.analytics'
import { Route as AuthenticatedBookDoctorIdRouteImport } from './routes/_authenticated/book.$doctorId'
import { Route as AuthenticatedAmbulanceFleetRouteImport } from './routes/_authenticated/ambulance.fleet'
import { Route as AuthenticatedAmbulanceDriverRouteImport } from './routes/_authenticated/ambulance.driver'
import { Route as AuthenticatedAmbulanceDashboardRouteImport } from './routes/_authenticated/ambulance.dashboard'
import { Route as AuthenticatedAdminSuperRouteImport } from './routes/_authenticated/admin.super'
import { Route as AuthenticatedAdminPharmacyRouteImport } from './routes/_authenticated/admin.pharmacy'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin.patients'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminHospitalsRouteImport } from './routes/_authenticated/admin.hospitals'
import { Route as AuthenticatedAdminEmergencyRouteImport } from './routes/_authenticated/admin.emergency'
import { Route as AuthenticatedAdminDoctorsRouteImport } from './routes/_authenticated/admin.doctors'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAdminAmbulanceRouteImport } from './routes/_authenticated/admin.ambulance'
import { Route as AuthenticatedDoctorPrescribeAppointmentIdRouteImport } from './routes/_authenticated/doctor.prescribe.$appointmentId'
import { Route as AuthenticatedDoctorPatientPatientIdRouteImport } from './routes/_authenticated/doctor.patient.$patientId'

const SignupHospitalRoute = SignupHospitalRouteImport.update({
  id: '/signup-hospital',
  path: '/signup-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupDoctorRoute = SignupDoctorRouteImport.update({
  id: '/signup-doctor',
  path: '/signup-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAmbulanceRoute = SignupAmbulanceRouteImport.update({
  id: '/signup-ambulance',
  path: '/signup-ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDoctorIdRoute = DoctorDoctorIdRouteImport.update({
  id: '/doctor/$doctorId',
  path: '/doctor/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultRoute = AuthenticatedConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookAmbulanceRoute =
  AuthenticatedBookAmbulanceRouteImport.update({
    id: '/book-ambulance',
    path: '/book-ambulance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplyDoctorRoute =
  AuthenticatedApplyDoctorRouteImport.update({
    id: '/apply-doctor',
    path: '/apply-doctor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVideoAppointmentIdRoute =
  AuthenticatedVideoAppointmentIdRouteImport.update({
    id: '/video/$appointmentId',
    path: '/video/$appointmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackOrderOrderIdRoute =
  AuthenticatedTrackOrderOrderIdRouteImport.update({
    id: '/track-order/$orderId',
    path: '/track-order/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackAmbulanceBookingIdRoute =
  AuthenticatedTrackAmbulanceBookingIdRouteImport.update({
    id: '/track-ambulance/$bookingId',
    path: '/track-ambulance/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayPaymentIdRoute =
  AuthenticatedPayPaymentIdRouteImport.update({
    id: '/pay/$paymentId',
    path: '/pay/$paymentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHospitalDepartmentsRoute =
  AuthenticatedHospitalDepartmentsRouteImport.update({
    id: '/hospital/departments',
    path: '/hospital/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHospitalDashboardRoute =
  AuthenticatedHospitalDashboardRouteImport.update({
    id: '/hospital/dashboard',
    path: '/hospital/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHospitalBranchesRoute =
  AuthenticatedHospitalBranchesRouteImport.update({
    id: '/hospital/branches',
    path: '/hospital/branches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHospitalBedsRoute =
  AuthenticatedHospitalBedsRouteImport.update({
    id: '/hospital/beds',
    path: '/hospital/beds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorWorkspaceRoute =
  AuthenticatedDoctorWorkspaceRouteImport.update({
    id: '/doctor/workspace',
    path: '/doctor/workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorTemplatesRoute =
  AuthenticatedDoctorTemplatesRouteImport.update({
    id: '/doctor/templates',
    path: '/doctor/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorScheduleRoute =
  AuthenticatedDoctorScheduleRouteImport.update({
    id: '/doctor/schedule',
    path: '/doctor/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorPatientsRoute =
  AuthenticatedDoctorPatientsRouteImport.update({
    id: '/doctor/patients',
    path: '/doctor/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorDashboardRoute =
  AuthenticatedDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorAnalyticsRoute =
  AuthenticatedDoctorAnalyticsRouteImport.update({
    id: '/doctor/analytics',
    path: '/doctor/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookDoctorIdRoute =
  AuthenticatedBookDoctorIdRouteImport.update({
    id: '/book/$doctorId',
    path: '/book/$doctorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAmbulanceFleetRoute =
  AuthenticatedAmbulanceFleetRouteImport.update({
    id: '/ambulance/fleet',
    path: '/ambulance/fleet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAmbulanceDriverRoute =
  AuthenticatedAmbulanceDriverRouteImport.update({
    id: '/ambulance/driver',
    path: '/ambulance/driver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAmbulanceDashboardRoute =
  AuthenticatedAmbulanceDashboardRouteImport.update({
    id: '/ambulance/dashboard',
    path: '/ambulance/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSuperRoute = AuthenticatedAdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPharmacyRoute =
  AuthenticatedAdminPharmacyRouteImport.update({
    id: '/admin/pharmacy',
    path: '/admin/pharmacy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/admin/invites',
    path: '/admin/invites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHospitalsRoute =
  AuthenticatedAdminHospitalsRouteImport.update({
    id: '/admin/hospitals',
    path: '/admin/hospitals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEmergencyRoute =
  AuthenticatedAdminEmergencyRouteImport.update({
    id: '/admin/emergency',
    path: '/admin/emergency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDoctorsRoute =
  AuthenticatedAdminDoctorsRouteImport.update({
    id: '/admin/doctors',
    path: '/admin/doctors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAmbulanceRoute =
  AuthenticatedAdminAmbulanceRouteImport.update({
    id: '/admin/ambulance',
    path: '/admin/ambulance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorPrescribeAppointmentIdRoute =
  AuthenticatedDoctorPrescribeAppointmentIdRouteImport.update({
    id: '/doctor/prescribe/$appointmentId',
    path: '/doctor/prescribe/$appointmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorPatientPatientIdRoute =
  AuthenticatedDoctorPatientPatientIdRouteImport.update({
    id: '/doctor/patient/$patientId',
    path: '/doctor/patient/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-ambulance': typeof SignupAmbulanceRoute
  '/signup-doctor': typeof SignupDoctorRoute
  '/signup-hospital': typeof SignupHospitalRoute
  '/apply-doctor': typeof AuthenticatedApplyDoctorRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/book-ambulance': typeof AuthenticatedBookAmbulanceRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/admin/ambulance': typeof AuthenticatedAdminAmbulanceRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/pharmacy': typeof AuthenticatedAdminPharmacyRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/ambulance/dashboard': typeof AuthenticatedAmbulanceDashboardRoute
  '/ambulance/driver': typeof AuthenticatedAmbulanceDriverRoute
  '/ambulance/fleet': typeof AuthenticatedAmbulanceFleetRoute
  '/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/doctor/analytics': typeof AuthenticatedDoctorAnalyticsRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/doctor/templates': typeof AuthenticatedDoctorTemplatesRoute
  '/doctor/workspace': typeof AuthenticatedDoctorWorkspaceRoute
  '/hospital/beds': typeof AuthenticatedHospitalBedsRoute
  '/hospital/branches': typeof AuthenticatedHospitalBranchesRoute
  '/hospital/dashboard': typeof AuthenticatedHospitalDashboardRoute
  '/hospital/departments': typeof AuthenticatedHospitalDepartmentsRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/pay/$paymentId': typeof AuthenticatedPayPaymentIdRoute
  '/track-ambulance/$bookingId': typeof AuthenticatedTrackAmbulanceBookingIdRoute
  '/track-order/$orderId': typeof AuthenticatedTrackOrderOrderIdRoute
  '/video/$appointmentId': typeof AuthenticatedVideoAppointmentIdRoute
  '/doctor/patient/$patientId': typeof AuthenticatedDoctorPatientPatientIdRoute
  '/doctor/prescribe/$appointmentId': typeof AuthenticatedDoctorPrescribeAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-ambulance': typeof SignupAmbulanceRoute
  '/signup-doctor': typeof SignupDoctorRoute
  '/signup-hospital': typeof SignupHospitalRoute
  '/apply-doctor': typeof AuthenticatedApplyDoctorRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/book-ambulance': typeof AuthenticatedBookAmbulanceRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/admin/ambulance': typeof AuthenticatedAdminAmbulanceRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/pharmacy': typeof AuthenticatedAdminPharmacyRoute
  '/admin/super': typeof AuthenticatedAdminSuperRoute
  '/ambulance/dashboard': typeof AuthenticatedAmbulanceDashboardRoute
  '/ambulance/driver': typeof AuthenticatedAmbulanceDriverRoute
  '/ambulance/fleet': typeof AuthenticatedAmbulanceFleetRoute
  '/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/doctor/analytics': typeof AuthenticatedDoctorAnalyticsRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/doctor/templates': typeof AuthenticatedDoctorTemplatesRoute
  '/doctor/workspace': typeof AuthenticatedDoctorWorkspaceRoute
  '/hospital/beds': typeof AuthenticatedHospitalBedsRoute
  '/hospital/branches': typeof AuthenticatedHospitalBranchesRoute
  '/hospital/dashboard': typeof AuthenticatedHospitalDashboardRoute
  '/hospital/departments': typeof AuthenticatedHospitalDepartmentsRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/pay/$paymentId': typeof AuthenticatedPayPaymentIdRoute
  '/track-ambulance/$bookingId': typeof AuthenticatedTrackAmbulanceBookingIdRoute
  '/track-order/$orderId': typeof AuthenticatedTrackOrderOrderIdRoute
  '/video/$appointmentId': typeof AuthenticatedVideoAppointmentIdRoute
  '/doctor/patient/$patientId': typeof AuthenticatedDoctorPatientPatientIdRoute
  '/doctor/prescribe/$appointmentId': typeof AuthenticatedDoctorPrescribeAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-ambulance': typeof SignupAmbulanceRoute
  '/signup-doctor': typeof SignupDoctorRoute
  '/signup-hospital': typeof SignupHospitalRoute
  '/_authenticated/apply-doctor': typeof AuthenticatedApplyDoctorRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/book-ambulance': typeof AuthenticatedBookAmbulanceRoute
  '/_authenticated/consult': typeof AuthenticatedConsultRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/_authenticated/admin/ambulance': typeof AuthenticatedAdminAmbulanceRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/_authenticated/admin/emergency': typeof AuthenticatedAdminEmergencyRoute
  '/_authenticated/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/pharmacy': typeof AuthenticatedAdminPharmacyRoute
  '/_authenticated/admin/super': typeof AuthenticatedAdminSuperRoute
  '/_authenticated/ambulance/dashboard': typeof AuthenticatedAmbulanceDashboardRoute
  '/_authenticated/ambulance/driver': typeof AuthenticatedAmbulanceDriverRoute
  '/_authenticated/ambulance/fleet': typeof AuthenticatedAmbulanceFleetRoute
  '/_authenticated/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/_authenticated/doctor/analytics': typeof AuthenticatedDoctorAnalyticsRoute
  '/_authenticated/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/_authenticated/doctor/patients': typeof AuthenticatedDoctorPatientsRoute
  '/_authenticated/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/_authenticated/doctor/templates': typeof AuthenticatedDoctorTemplatesRoute
  '/_authenticated/doctor/workspace': typeof AuthenticatedDoctorWorkspaceRoute
  '/_authenticated/hospital/beds': typeof AuthenticatedHospitalBedsRoute
  '/_authenticated/hospital/branches': typeof AuthenticatedHospitalBranchesRoute
  '/_authenticated/hospital/dashboard': typeof AuthenticatedHospitalDashboardRoute
  '/_authenticated/hospital/departments': typeof AuthenticatedHospitalDepartmentsRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/pay/$paymentId': typeof AuthenticatedPayPaymentIdRoute
  '/_authenticated/track-ambulance/$bookingId': typeof AuthenticatedTrackAmbulanceBookingIdRoute
  '/_authenticated/track-order/$orderId': typeof AuthenticatedTrackOrderOrderIdRoute
  '/_authenticated/video/$appointmentId': typeof AuthenticatedVideoAppointmentIdRoute
  '/_authenticated/doctor/patient/$patientId': typeof AuthenticatedDoctorPatientPatientIdRoute
  '/_authenticated/doctor/prescribe/$appointmentId': typeof AuthenticatedDoctorPrescribeAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/signup-ambulance'
    | '/signup-doctor'
    | '/signup-hospital'
    | '/apply-doctor'
    | '/appointments'
    | '/book-ambulance'
    | '/consult'
    | '/dashboard'
    | '/doctors'
    | '/nearby'
    | '/payments'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/doctor/$doctorId'
    | '/admin/ambulance'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/emergency'
    | '/admin/hospitals'
    | '/admin/invites'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/pharmacy'
    | '/admin/super'
    | '/ambulance/dashboard'
    | '/ambulance/driver'
    | '/ambulance/fleet'
    | '/book/$doctorId'
    | '/doctor/analytics'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/schedule'
    | '/doctor/templates'
    | '/doctor/workspace'
    | '/hospital/beds'
    | '/hospital/branches'
    | '/hospital/dashboard'
    | '/hospital/departments'
    | '/invite/$token'
    | '/pay/$paymentId'
    | '/track-ambulance/$bookingId'
    | '/track-order/$orderId'
    | '/video/$appointmentId'
    | '/doctor/patient/$patientId'
    | '/doctor/prescribe/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/signup-ambulance'
    | '/signup-doctor'
    | '/signup-hospital'
    | '/apply-doctor'
    | '/appointments'
    | '/book-ambulance'
    | '/consult'
    | '/dashboard'
    | '/doctors'
    | '/nearby'
    | '/payments'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/doctor/$doctorId'
    | '/admin/ambulance'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/emergency'
    | '/admin/hospitals'
    | '/admin/invites'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/pharmacy'
    | '/admin/super'
    | '/ambulance/dashboard'
    | '/ambulance/driver'
    | '/ambulance/fleet'
    | '/book/$doctorId'
    | '/doctor/analytics'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/schedule'
    | '/doctor/templates'
    | '/doctor/workspace'
    | '/hospital/beds'
    | '/hospital/branches'
    | '/hospital/dashboard'
    | '/hospital/departments'
    | '/invite/$token'
    | '/pay/$paymentId'
    | '/track-ambulance/$bookingId'
    | '/track-order/$orderId'
    | '/video/$appointmentId'
    | '/doctor/patient/$patientId'
    | '/doctor/prescribe/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/signup-ambulance'
    | '/signup-doctor'
    | '/signup-hospital'
    | '/_authenticated/apply-doctor'
    | '/_authenticated/appointments'
    | '/_authenticated/book-ambulance'
    | '/_authenticated/consult'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors'
    | '/_authenticated/nearby'
    | '/_authenticated/payments'
    | '/_authenticated/pharmacy'
    | '/_authenticated/prescriptions'
    | '/_authenticated/profile'
    | '/doctor/$doctorId'
    | '/_authenticated/admin/ambulance'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/doctors'
    | '/_authenticated/admin/emergency'
    | '/_authenticated/admin/hospitals'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/pharmacy'
    | '/_authenticated/admin/super'
    | '/_authenticated/ambulance/dashboard'
    | '/_authenticated/ambulance/driver'
    | '/_authenticated/ambulance/fleet'
    | '/_authenticated/book/$doctorId'
    | '/_authenticated/doctor/analytics'
    | '/_authenticated/doctor/dashboard'
    | '/_authenticated/doctor/patients'
    | '/_authenticated/doctor/schedule'
    | '/_authenticated/doctor/templates'
    | '/_authenticated/doctor/workspace'
    | '/_authenticated/hospital/beds'
    | '/_authenticated/hospital/branches'
    | '/_authenticated/hospital/dashboard'
    | '/_authenticated/hospital/departments'
    | '/_authenticated/invite/$token'
    | '/_authenticated/pay/$paymentId'
    | '/_authenticated/track-ambulance/$bookingId'
    | '/_authenticated/track-order/$orderId'
    | '/_authenticated/video/$appointmentId'
    | '/_authenticated/doctor/patient/$patientId'
    | '/_authenticated/doctor/prescribe/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SignupAmbulanceRoute: typeof SignupAmbulanceRoute
  SignupDoctorRoute: typeof SignupDoctorRoute
  SignupHospitalRoute: typeof SignupHospitalRoute
  DoctorDoctorIdRoute: typeof DoctorDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-hospital': {
      id: '/signup-hospital'
      path: '/signup-hospital'
      fullPath: '/signup-hospital'
      preLoaderRoute: typeof SignupHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-doctor': {
      id: '/signup-doctor'
      path: '/signup-doctor'
      fullPath: '/signup-doctor'
      preLoaderRoute: typeof SignupDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-ambulance': {
      id: '/signup-ambulance'
      path: '/signup-ambulance'
      fullPath: '/signup-ambulance'
      preLoaderRoute: typeof SignupAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$doctorId': {
      id: '/doctor/$doctorId'
      path: '/doctor/$doctorId'
      fullPath: '/doctor/$doctorId'
      preLoaderRoute: typeof DoctorDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consult': {
      id: '/_authenticated/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof AuthenticatedConsultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book-ambulance': {
      id: '/_authenticated/book-ambulance'
      path: '/book-ambulance'
      fullPath: '/book-ambulance'
      preLoaderRoute: typeof AuthenticatedBookAmbulanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply-doctor': {
      id: '/_authenticated/apply-doctor'
      path: '/apply-doctor'
      fullPath: '/apply-doctor'
      preLoaderRoute: typeof AuthenticatedApplyDoctorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/video/$appointmentId': {
      id: '/_authenticated/video/$appointmentId'
      path: '/video/$appointmentId'
      fullPath: '/video/$appointmentId'
      preLoaderRoute: typeof AuthenticatedVideoAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/track-order/$orderId': {
      id: '/_authenticated/track-order/$orderId'
      path: '/track-order/$orderId'
      fullPath: '/track-order/$orderId'
      preLoaderRoute: typeof AuthenticatedTrackOrderOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/track-ambulance/$bookingId': {
      id: '/_authenticated/track-ambulance/$bookingId'
      path: '/track-ambulance/$bookingId'
      fullPath: '/track-ambulance/$bookingId'
      preLoaderRoute: typeof AuthenticatedTrackAmbulanceBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pay/$paymentId': {
      id: '/_authenticated/pay/$paymentId'
      path: '/pay/$paymentId'
      fullPath: '/pay/$paymentId'
      preLoaderRoute: typeof AuthenticatedPayPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hospital/departments': {
      id: '/_authenticated/hospital/departments'
      path: '/hospital/departments'
      fullPath: '/hospital/departments'
      preLoaderRoute: typeof AuthenticatedHospitalDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hospital/dashboard': {
      id: '/_authenticated/hospital/dashboard'
      path: '/hospital/dashboard'
      fullPath: '/hospital/dashboard'
      preLoaderRoute: typeof AuthenticatedHospitalDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hospital/branches': {
      id: '/_authenticated/hospital/branches'
      path: '/hospital/branches'
      fullPath: '/hospital/branches'
      preLoaderRoute: typeof AuthenticatedHospitalBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hospital/beds': {
      id: '/_authenticated/hospital/beds'
      path: '/hospital/beds'
      fullPath: '/hospital/beds'
      preLoaderRoute: typeof AuthenticatedHospitalBedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/workspace': {
      id: '/_authenticated/doctor/workspace'
      path: '/doctor/workspace'
      fullPath: '/doctor/workspace'
      preLoaderRoute: typeof AuthenticatedDoctorWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/templates': {
      id: '/_authenticated/doctor/templates'
      path: '/doctor/templates'
      fullPath: '/doctor/templates'
      preLoaderRoute: typeof AuthenticatedDoctorTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/schedule': {
      id: '/_authenticated/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof AuthenticatedDoctorScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/patients': {
      id: '/_authenticated/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/dashboard': {
      id: '/_authenticated/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/analytics': {
      id: '/_authenticated/doctor/analytics'
      path: '/doctor/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof AuthenticatedDoctorAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book/$doctorId': {
      id: '/_authenticated/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof AuthenticatedBookDoctorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambulance/fleet': {
      id: '/_authenticated/ambulance/fleet'
      path: '/ambulance/fleet'
      fullPath: '/ambulance/fleet'
      preLoaderRoute: typeof AuthenticatedAmbulanceFleetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambulance/driver': {
      id: '/_authenticated/ambulance/driver'
      path: '/ambulance/driver'
      fullPath: '/ambulance/driver'
      preLoaderRoute: typeof AuthenticatedAmbulanceDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambulance/dashboard': {
      id: '/_authenticated/ambulance/dashboard'
      path: '/ambulance/dashboard'
      fullPath: '/ambulance/dashboard'
      preLoaderRoute: typeof AuthenticatedAmbulanceDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/super': {
      id: '/_authenticated/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AuthenticatedAdminSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pharmacy': {
      id: '/_authenticated/admin/pharmacy'
      path: '/admin/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AuthenticatedAdminPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hospitals': {
      id: '/_authenticated/admin/hospitals'
      path: '/admin/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AuthenticatedAdminHospitalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/emergency': {
      id: '/_authenticated/admin/emergency'
      path: '/admin/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AuthenticatedAdminEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/doctors': {
      id: '/_authenticated/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ambulance': {
      id: '/_authenticated/admin/ambulance'
      path: '/admin/ambulance'
      fullPath: '/admin/ambulance'
      preLoaderRoute: typeof AuthenticatedAdminAmbulanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/prescribe/$appointmentId': {
      id: '/_authenticated/doctor/prescribe/$appointmentId'
      path: '/doctor/prescribe/$appointmentId'
      fullPath: '/doctor/prescribe/$appointmentId'
      preLoaderRoute: typeof AuthenticatedDoctorPrescribeAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor/patient/$patientId': {
      id: '/_authenticated/doctor/patient/$patientId'
      path: '/doctor/patient/$patientId'
      fullPath: '/doctor/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedDoctorPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApplyDoctorRoute: typeof AuthenticatedApplyDoctorRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBookAmbulanceRoute: typeof AuthenticatedBookAmbulanceRoute
  AuthenticatedConsultRoute: typeof AuthenticatedConsultRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAmbulanceRoute: typeof AuthenticatedAdminAmbulanceRoute
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDoctorsRoute: typeof AuthenticatedAdminDoctorsRoute
  AuthenticatedAdminEmergencyRoute: typeof AuthenticatedAdminEmergencyRoute
  AuthenticatedAdminHospitalsRoute: typeof AuthenticatedAdminHospitalsRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPharmacyRoute: typeof AuthenticatedAdminPharmacyRoute
  AuthenticatedAdminSuperRoute: typeof AuthenticatedAdminSuperRoute
  AuthenticatedAmbulanceDashboardRoute: typeof AuthenticatedAmbulanceDashboardRoute
  AuthenticatedAmbulanceDriverRoute: typeof AuthenticatedAmbulanceDriverRoute
  AuthenticatedAmbulanceFleetRoute: typeof AuthenticatedAmbulanceFleetRoute
  AuthenticatedBookDoctorIdRoute: typeof AuthenticatedBookDoctorIdRoute
  AuthenticatedDoctorAnalyticsRoute: typeof AuthenticatedDoctorAnalyticsRoute
  AuthenticatedDoctorDashboardRoute: typeof AuthenticatedDoctorDashboardRoute
  AuthenticatedDoctorPatientsRoute: typeof AuthenticatedDoctorPatientsRoute
  AuthenticatedDoctorScheduleRoute: typeof AuthenticatedDoctorScheduleRoute
  AuthenticatedDoctorTemplatesRoute: typeof AuthenticatedDoctorTemplatesRoute
  AuthenticatedDoctorWorkspaceRoute: typeof AuthenticatedDoctorWorkspaceRoute
  AuthenticatedHospitalBedsRoute: typeof AuthenticatedHospitalBedsRoute
  AuthenticatedHospitalBranchesRoute: typeof AuthenticatedHospitalBranchesRoute
  AuthenticatedHospitalDashboardRoute: typeof AuthenticatedHospitalDashboardRoute
  AuthenticatedHospitalDepartmentsRoute: typeof AuthenticatedHospitalDepartmentsRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedPayPaymentIdRoute: typeof AuthenticatedPayPaymentIdRoute
  AuthenticatedTrackAmbulanceBookingIdRoute: typeof AuthenticatedTrackAmbulanceBookingIdRoute
  AuthenticatedTrackOrderOrderIdRoute: typeof AuthenticatedTrackOrderOrderIdRoute
  AuthenticatedVideoAppointmentIdRoute: typeof AuthenticatedVideoAppointmentIdRoute
  AuthenticatedDoctorPatientPatientIdRoute: typeof AuthenticatedDoctorPatientPatientIdRoute
  AuthenticatedDoctorPrescribeAppointmentIdRoute: typeof AuthenticatedDoctorPrescribeAppointmentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplyDoctorRoute: AuthenticatedApplyDoctorRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBookAmbulanceRoute: AuthenticatedBookAmbulanceRoute,
  AuthenticatedConsultRoute: AuthenticatedConsultRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAmbulanceRoute: AuthenticatedAdminAmbulanceRoute,
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDoctorsRoute: AuthenticatedAdminDoctorsRoute,
  AuthenticatedAdminEmergencyRoute: AuthenticatedAdminEmergencyRoute,
  AuthenticatedAdminHospitalsRoute: AuthenticatedAdminHospitalsRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPharmacyRoute: AuthenticatedAdminPharmacyRoute,
  AuthenticatedAdminSuperRoute: AuthenticatedAdminSuperRoute,
  AuthenticatedAmbulanceDashboardRoute: AuthenticatedAmbulanceDashboardRoute,
  AuthenticatedAmbulanceDriverRoute: AuthenticatedAmbulanceDriverRoute,
  AuthenticatedAmbulanceFleetRoute: AuthenticatedAmbulanceFleetRoute,
  AuthenticatedBookDoctorIdRoute: AuthenticatedBookDoctorIdRoute,
  AuthenticatedDoctorAnalyticsRoute: AuthenticatedDoctorAnalyticsRoute,
  AuthenticatedDoctorDashboardRoute: AuthenticatedDoctorDashboardRoute,
  AuthenticatedDoctorPatientsRoute: AuthenticatedDoctorPatientsRoute,
  AuthenticatedDoctorScheduleRoute: AuthenticatedDoctorScheduleRoute,
  AuthenticatedDoctorTemplatesRoute: AuthenticatedDoctorTemplatesRoute,
  AuthenticatedDoctorWorkspaceRoute: AuthenticatedDoctorWorkspaceRoute,
  AuthenticatedHospitalBedsRoute: AuthenticatedHospitalBedsRoute,
  AuthenticatedHospitalBranchesRoute: AuthenticatedHospitalBranchesRoute,
  AuthenticatedHospitalDashboardRoute: AuthenticatedHospitalDashboardRoute,
  AuthenticatedHospitalDepartmentsRoute: AuthenticatedHospitalDepartmentsRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedPayPaymentIdRoute: AuthenticatedPayPaymentIdRoute,
  AuthenticatedTrackAmbulanceBookingIdRoute:
    AuthenticatedTrackAmbulanceBookingIdRoute,
  AuthenticatedTrackOrderOrderIdRoute: AuthenticatedTrackOrderOrderIdRoute,
  AuthenticatedVideoAppointmentIdRoute: AuthenticatedVideoAppointmentIdRoute,
  AuthenticatedDoctorPatientPatientIdRoute:
    AuthenticatedDoctorPatientPatientIdRoute,
  AuthenticatedDoctorPrescribeAppointmentIdRoute:
    AuthenticatedDoctorPrescribeAppointmentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SignupAmbulanceRoute: SignupAmbulanceRoute,
  SignupDoctorRoute: SignupDoctorRoute,
  SignupHospitalRoute: SignupHospitalRoute,
  DoctorDoctorIdRoute: DoctorDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
